openapi: 3.0.0
info:
  title: Weather APP
  version: "1.0"
paths:
  /api/auth/register:
    post:
      summary: Register a new user
      operationId: modules.auth.routes.register
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '201':
          description: User created, access_token set in cookie
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/login:
    post:
      summary: Login a user
      operationId: modules.auth.routes.login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: User logged in, access_token returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/logout:
    post:
      summary: Logout a user
      operationId: modules.auth.routes.logout
      tags:
        - auth
      responses:
        '200':
          description: Successfully logged out
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LogoutResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/weather/cities:
    get:
      summary: Get a list of cities
      operationId: modules.weather.routes.get_cities
      tags:
        - weather
      parameters:
        - name: min_population
          in: query
          required: false
          schema:
            type: integer
          description: Minimum population of the cities to be returned
        - name: name_prefix
          in: query
          required: false
          schema:
            type: string
          description: Prefix of the city names to be returned
      responses:
        '200':
          description: Successfully logged out
          content:
            application/json:
              schema:
                type:
                  array
                items:
                  $ref: '#/components/schemas/LogoutResponse'

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          format: password

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
          format: password

    UserResponse:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        created_at:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string

    LogoutResponse:
      type: object
      properties:
        message:
          type: string

    CityResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
